#+title: Dotfiles
#+description: A collection of my various configuration and dotfiles
#+author: Gardner Berry

* Outline
These configuration files are made for arch linux and arch based distros so I can't garante its functionality on all my main distro is EndeavourOS. I any one wants to test my configs you are welcome to and please file bug reports, but I dont really have the time right now to do tests on multible distros.

* Dependancies
** awesome
- nemo
- [[https://github.com/doomemacs/doomemacs][Doom Emacs]]
- brave-bin
- librewolf-bin
- alacritty
- fish
- lxapperance
- nitrogen
- neovim
** alacritty
- alacritty-themes
** fish
- pokemon-colorscripts-git
- pfetch
- neofetch
- exa
- [[https://starship.rs][Starship Prompt]]
** bash
- neofetch
- exa
- [[https://starship.rs][Starship Prompt]]
- pfetch
- pokemon-colorscripts-git

* How to install my configs
** Recommended packages
*** You can just copy and paste this and it should install everything
#+BEGIN_SRC
yay -S awesome dmenu picom brave-bin librewolf-bin starship exa btop pfetch pokemon-colorscripts-git lxapperance emacs nemo alacritty zsh alacritty-themes lxappearance nitrogen fish neovim ripgrep fd chromium
#+END_SRC
** .bashrc
*** Copy and Past this to use my .bashrc
#+BEGIN_SRC
cp -r ~/dotfiles/bash/.bashrc ~/
#+END_SRC
** fish
*** Copy and past to install my fish configs
#+BEGIN_SRC
cp -r ~/dotfiles/fish ~/.config
#+END_SRC
** alacrity
*** Copy and paste for my alacritty config
#+BEGIN_SRC
cp -r ~/dofiles/alacritty ~/.config
#+END_SRC
** awesome
*** Copy and paste for my awesomewm config
#+BEGIN_SRC
cp -r ~/dotfiles/awesome ~/.config
#+END_SRC
*** How to make my config the default fall back config
#+BEGIN_SRC
sudo cp -r ~/dotfiles/awesome/rc.lua /etc/xdg/awesome
#+END_SRC
** Doom Emacs
*** How to copy my Doom Emacs config
#+BEGIN_EXAMPLE
cp -r ~/dotfiles/.doom.d ~/
#+END_EXAMPLE
** .zsh
*** How to install my Zsh config
#+BEGIN_SRC
cp -r ~/dotfiles/zsh/.zshrc ~/
#+END_SRC

* Future Plans
I think that I will eventually make a shell script to install all of my configs but that may be a bit far off. I am also currently testing my configs on NixOS so we will see where that goes.
